export const POST_TO_LIST_REQUEST = "POST_TO_LIST_REQUEST";
export const POST_TO_LIST_SUCCESS = "POST_TO_LIST_SUCCESS";
export const POST_TO_LIST_FAILURE = "POST_TO_LIST_FAILURE";


export const GET_TO_LIST_REQUEST = "POST_TO_LIST_REQUEST";
export const GET_TO_LIST_SUCCESS = "POST_TO_LIST_SUCCESS";
export const GET_TO_LIST_FAILURE = "POST_TO_LIST_FAILURE";


export const POST_EVENT_REQUEST = "POST_EVENT_REQUEST";
export const POST_EVENT_SUCCESS = "POST_EVENT_SUCCESS";
export const POST_EVENT_FAILURE = "POST_EVENT_FAILURE";


export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAILURE = "GET_EVENT_FAILURE";


export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";

